# .github/workflows/ci.yml

name: Run Tests 

on:
  push: 
    branches:
      - main 
  pull_request: 
    branches:
      - main 

jobs: 
  test-backend: 
    name: Test Backend (Python)
    runs-on: ubuntu-latest 

    steps: 
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Set up Python 
        uses: actions/setup-python@v3
        with:
          python-version: '3.9' 

      - name: Install dependencies (Backend) 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Если у тебя есть requirements.txt для бэкенда

      - name: Run Pytest 
        run: pytest 

  test-frontend: 
    name: Test Frontend (React)
    runs-on: ubuntu-latest

    defaults: 
      run:
        working-directory: ./frontend 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Install dependencies (Frontend) 
        run: npm install 

      - name: Run Frontend Tests 
        run: npm test 
